language: cpp
os:
  - osx
  - linux
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../
  - make install
deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file:
    - "install/bin/emmy_core.so"
    - "install/bin/emmy_core.dylib"
  skip_cleanup: true
  draft: false
  on:
    tags: true